baseURL: "https://yyq83.github.io/notion-ghpages"
title: ğŸ§‘â€ğŸš€ ä¸€æ ¹è—¤ä¸Šä¸ƒæœµèŠ±
theme: PaperMod

paginate: 5
enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
  disableXML: true

outputs:
  home:
    - HTML
    - JSON

menu:
  main:
    - name: å½’æ¡£
      url: categories/
      weight: 1
    - name: æ ‡ç­¾
      url: tags/
      weight: 2
    - name: æœç´¢
      url: search/
      weight: 3
    - name: å‹æƒ…é“¾æ¥
      url: https://yangyinqi.top/links
      weight: 4

params:
  env: production
  description: "Blog made from Notion with Hugo, hosted on GitHub Pages"
  keywords: [blog, hugo, notion, github]
  defaultTheme: light
  disableThemeToggle: true
  disableSpecial1stPost: true
  ShowCodeCopyButtons: true
  ShowToc: true
  ShowReadingTime: true

  mainSections:
    - posts

  profileMode:
    enabled: false
    title: Blog template
    # imageUrl: "avatar.png"
    # imageTitle: ""
    # imageWidth: 120
    # imageHeight: 120
    subtitle: "Blog made from Notion with Hugo and GitHub Pages"

  homeInfoPatams:
    Title:  ğŸ‘‹ Welcom to Yinqi'Log
    Content: >
      Hi, æˆ‘æ˜¯ä¸€æ ¹è—¤ä¸Šä¸ƒæœµèŠ±ã€‚ğŸ‘‹

      - æˆ‘æ˜¯ä¸€æšç”Ÿç‰©ä¿¡æ¯ä»ä¸šè€…ã€‚

      - çˆ±å¥½ é˜…è¯»ã€ä»£ç ã€å‘å‘†ã€‚

      - æˆ‘åœ¨è¿™é‡Œä¹¦å†™âœğŸ»æˆ‘çš„ å­¦ä¹ ç¬”è®° ä»¥åŠ è®°å½•æˆ‘çš„ç”Ÿæ´»ğŸ“·ã€‚


  socialIcons:
    - name: email
      url: "yangyinqi85@gmail.com"
    - name: github
      url: "https://github.com/yyq83"
      

  # label:
  #   text: ""
  #   icon: "avatar.png"
  #   iconHeight: 30
  
  # assets:
  #   favicon: "favicons/favicon.ico"
  #   favicon16x16:  "favicons/favicon-16x16.png"
  #   favicon32x32:  "favicons/favicon-32x32.png"
  #   apple_touch_icon:  "favicons/apple-touch-icon.png"
  #   safari_pinned_tab:  "favicons/favicon.ico"

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

markup:
  goldmark:
    renderer:
      unsafe: true
